// movies-app-solid/src/components/Reviews/index.tsx
import { Accessor, Component, Index, Show } from 'solid-js';
import styles from './style.module.scss';
import { Review } from '../../models';
import Loader from '../Loader';

interface IReviews {
    reviews: Accessor<Review[]>;
    isLoading: Accessor<boolean>;
}

const Reviews: Component<IReviews> = ({ reviews, isLoading }) => {
    return (
        <div class={styles.reviews}>
            <Index each={reviews()}>
                {(review) => (
                    <div
                        classList={{
                            'chat chat-start': true,
                            [styles.reviews__review]: true
                        }}
                    >
                        <div
                            classList={{
                                'chat-image avatar': true,
                                [styles.reviews__review__avatar]: true
                            }}
                        >
                            <div class='w-10 rounded-full'>
                                {review().profilePic && (
                                    <img loading='lazy' src={review().profilePic} alt={review().authorName} />
                                )}
                            </div>
                        </div>
                        <div
                            classList={{
                                'chat-header': true,
                                [styles.reviews__review__author]: true
                            }}
                        >
                            {review().authorName}
                        </div>
                        <div
                            classList={{
                                'chat-bubble': true,
                                [styles.reviews__review__content]: true
                            }}
                        >
                            {review().content}
                        </div>
                    </div>
                )
                }
            </Index >
            <Show when={reviews().length === 0 && !isLoading()}>
                <h4 class={styles.no_reviews}>No Reviews Found...</h4>
            </Show>
            <Show when={isLoading()}>
                <Loader />
            </Show>
        </div >
    );
};

export default Reviews;

// movies-app-react/src/components/Reviews/index.tsx
import styles from './style.module.scss';
import { classNames } from '../../utils';
import { Review } from '../../models';

interface IReviews {
  reviews: Review[];
  isLoading?: boolean;
}

const Reviews: React.FC<IReviews> = ({ reviews, isLoading }) => {
  return (
    <div className={styles.reviews}>
      {reviews.map((review) => (
        <div
          key={review.id}
          className={classNames('chat chat-start', styles.reviews__review)}
        >
          <div
            className={classNames(
              'chat-image avatar',
              styles.reviews__review__avatar
            )}
          >
            <div className='w-10 rounded-full'>
              {review.profilePic && (
                <img loading='lazy' src={review.profilePic} />
              )}
            </div>
          </div>
          <div
            className={classNames(
              'chat-header',
              styles.reviews__review__author
            )}
          >
            {review.authorName}
          </div>
          <div
            className={classNames(
              'chat-bubble',
              styles.reviews__review__content
            )}
          >
            {review.content}
          </div>
        </div>
      ))}
      {reviews.length === 0 && !isLoading && (
        <h4 className={styles.no_reviews}>No Reviews Found...</h4>
      )}
    </div>
  );
};

export default Reviews;
