// movies-app-solid/src/components/Header/index.tsx
import { Component, For, createMemo } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import styles from './style.module.scss';
import { Page } from '../../models';
import { classNames } from '../../utils';
import logo from '../../assets/logo.svg';

interface IHeader {
  pages: Page[];
}

export const Header: Component<IHeader> = ({ pages }) => {
  const location = useLocation();
  const pathname = createMemo(() => location.pathname);

  return (
    <header class={styles.header}>
      <div class={classNames('container', styles.header__container)}>
        <nav class={styles.header__nav}>
          <A
            href={'/'}
            class={styles.header__logo}
            aria-label='Home'
          >
            <img src={logo} alt='TMDB' />
          </A>
          <ul class={styles.header__menus}>
            <For each={pages}>
              {(page) => (
                <li
                  classList={{
                    [styles.header__menus__menu]: true,
                    [styles['header__menus__menu--active']]:
                      pathname() === page.path
                  }}
                >
                  <A href={page.path} aria-label={page.title}>
                    {page.title}
                  </A>
                </li>
              )}
            </For>
          </ul>
        </nav>
      </div>
    </header>
  );
};

// movies-app-react/src/components/Header/index.tsx
import styles from './style.module.scss';
import logo from '../../assets/logo.svg';
import { Link, useLocation } from 'react-router-dom';
import { PAGES } from '../../constants/routes';
import { classNames } from '../../utils';

interface IHeader {}

export const Header: React.FC<IHeader> = ({}) => {
  const location = useLocation();
  const pathName = location.pathname;

  return (
    <header className={styles.header}>
      <div className={classNames('container', styles.header__container)}>
        <nav className={styles.header__nav}>
          <Link to={'/'} className={styles.header__logo} aria-label="Home">
            <img src={logo} alt="TMDB" />
          </Link>
          <ul className={styles.header__menus}>
            {PAGES.map((page, i) => (
              <li
                key={i}
                className={classNames(
                  styles.header__menus__menu,
                  pathName === page.path && styles.header__menus__active_menu
                )}
              >
                <Link to={page.path} aria-label={page.title}>
                  {page.title}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </header>
  );
};
