// movies-app-solid/src/pages/Movies/index.tsx
import styles from './style.module.scss';
import { WelcomeHeader } from '../../components/WelcomeHeader';
import { SearchInput } from '../../components/SearchInput';
import { useMovies } from '../../hooks/useMovies';
import MoviesList from '../../components/MoviesList';
import { useIsRouting } from '@solidjs/router';
import { Movies } from '../../models';
import { Show } from 'solid-js';

export default function MoviesPage() {
  const { query, movies, page, totalPages, isLoading, setQuery, loadMore } = useMovies();
  const isRouting = useIsRouting();

  const onLoadMore = () => {
    loadMore();
  };

  return (
    <div class='container'>
      <WelcomeHeader />
      <SearchInput
        value={query}
        onChange={setQuery}
        className={styles.movies_search_input}
      />
      <div class={styles.list}>
        <MoviesList 
          movies={movies} 
          isLoading={isLoading} 
          isRouting={isRouting} 
          isLoadMoreLoading={() => page() > 1}
          />
      </div>
      <Show when={totalPages() > 1}>
        <div class={styles.load_more}>
          <button
            class='btn btn-neutral'
            disabled={isLoading()}
            onClick={onLoadMore}
          >
            {isLoading() ? 'Please wait...' : 'Load More'}
          </button>
        </div>
      </Show>
    </div>
  );
}

// movies-app-react/src/pages/Movies/index.tsx
import { memo, useCallback, useEffect } from 'react';
import styles from './style.module.scss';
import { useMovies, useMoviesDispatch } from '../../hooks/useMovies';
import SearchInputBar from '../../components/SearchInpurBar';
import MoviesList from '../../components/MoviesList';
import {
  SET_CATEGORY,
  SET_CURRENT_PAGE,
  SET_QUERY
} from '../../contexts/MoviesContext';

export default function MoviesPage({
  category = '/popular'
}: {
  category?: string;
}) {
  const { movies, isLoading, page, totalPages, query, isCategoryLoading } = useMovies();
  const dispatch = useMoviesDispatch();

  useEffect(() => {
    dispatch({ type: SET_CATEGORY, category: category });
  }, [category]);

  const onSearch = useCallback(
    (value: string) => {
      dispatch({ type: SET_QUERY, query: value });
    },
    [dispatch]
  );

  const onLoadMore = useCallback(() => {
    if (page < totalPages) {
      dispatch({ type: SET_CURRENT_PAGE, page: page + 1 });
    }
  }, [dispatch, page, totalPages]);

  return (
    <div className='container'>
      <WelcomeHeader />
      <SearchInputBar value={query} onChange={onSearch} isLoading={isLoading} />
      <div className={styles.list}>
        <MoviesList
          movies={movies}
          isLoading={isLoading}
          isCategoryLoading={isCategoryLoading}
        />
      </div>
      {totalPages > 1 && (
        <div className={styles.load_more}>
          <button
            className='btn btn-neutral'
            disabled={isLoading}
            onClick={onLoadMore}
          >
            {isLoading ? 'Please wait...' : 'Load More'}
          </button>
        </div>
      )}
    </div>
  );
}

const WelcomeHeader: React.FC = memo(() => {
  return (
    <div className={styles.welcome_header}>
      <h1>Welcome.</h1>
      <h2>Millions of movies to discover. Explore now.</h2>
    </div>
  );
});
