// movies-app-react/src/contexts/MovieContext.tsx
import {
  createContext,
  ReactNode,
  useEffect,
  useMemo,
  useReducer,
  useState
} from 'react';
import { Movie, Review, Trailer } from '../models';
import MoviesService from '../services/MoviesService';
import { useParams } from 'react-router-dom';

export const SET_MOVIE = 'SET_MOVIE';
export const SET_MOVIE_REVIEWS = 'SET_MOVIE_REVIEWS';
export const SET_MOVIE_TRAILERS = 'SET_MOVIE_TRAILERS';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_REVIES_LOADING = 'SET_REVIES_LOADING';
export const SET_TRAILERS_LOADING = 'SET_TRAILERS_LOADING';

export interface IMovieState {
  movie: Movie | null;
  reviews: Review[];
  trailers: Trailer[];
  error: any;
  isReviewsLoaded: boolean;
  isTrailersLoaded: boolean;
  isLoading: boolean;
  isReviewsLoading: boolean;
  isTrailersLoading: boolean;
}

export interface MovieContextType extends IMovieState {
  selectedTab: string;
  setSelectedTab: (tab: string) => void;
}

export const MovieContext = createContext<MovieContextType>(
  {} as MovieContextType
);
export const MovieDispatchContext = createContext<any>(null);

type MovieAction =
  | { type: typeof SET_MOVIE; movie: Movie | null }
  | { type: typeof SET_MOVIE_REVIEWS; reviews: Review[] }
  | { type: typeof SET_MOVIE_TRAILERS; trailers: Trailer[] }
  | { type: typeof SET_ERROR; error: string }
  | { type: typeof SET_LOADING; isLoading: boolean }
  | { type: typeof SET_REVIES_LOADING; isLoading: boolean }
  | { type: typeof SET_TRAILERS_LOADING; isLoading: boolean };

const movieReducer = (state: IMovieState, action: MovieAction) => {
  switch (action.type) {
    case SET_MOVIE:
      return {
        ...state,
        movie: action.movie,
        isLoading: false
      };
    case SET_MOVIE_REVIEWS:
      return {
        ...state,
        reviews: action.reviews,
        isLoading: false,
        isReviewsLoaded: true
      };
    case SET_MOVIE_TRAILERS:
      return {
        ...state,
        trailers: action.trailers,
        isLoading: false,
        isTrailersLoaded: true
      };
    case SET_ERROR:
      return {
        ...state,
        error: action.error,
        isLoading: false
      };
    case SET_LOADING:
      return {
        ...state,
        isLoading: action.isLoading,
        error: null
      };
    case SET_REVIES_LOADING:
      return {
        ...state,
        isReviewsLoading: action.isLoading
      };
    case SET_TRAILERS_LOADING:
      return {
        ...state,
        isTrailersLoading: action.isLoading
      };
    default:
      return state;
  }
};

const initialState: IMovieState = {
  movie: null,
  reviews: [],
  trailers: [],
  isReviewsLoaded: false,
  isTrailersLoaded: false,
  isLoading: true,
  isReviewsLoading: true,
  isTrailersLoading: true,
  error: null
};

export function MovieProvider({ children }: { children: ReactNode }): any {
  const params = useParams();
  const { id } = params;

  const [state, dispatch] = useReducer(movieReducer, initialState);

  const [selectedTab, setSelectedTab] = useState('reviews');

  useEffect(() => {
    const controller = new AbortController();
    id && getMovie({ controller });
    return () => {
      controller.abort();
    };
  }, [id]);

  useEffect(() => {
    const controller = new AbortController();
    id &&
      selectedTab === 'reviews' &&
      !state.isReviewsLoaded &&
      getMovieReviews({ controller });
    id &&
      selectedTab === 'trailers' &&
      !state.isTrailersLoaded &&
      getMovieTrailers({ controller });
    return () => {
      controller.abort();
    };
  }, [id, selectedTab, state.isReviewsLoaded, state.isTrailersLoaded]);

  async function getMovie({ controller }: { controller: AbortController }) {
    dispatch({ type: SET_LOADING, isLoading: true });
    try {
      const movie = await MoviesService.getMovieById(
        {
          id: id
        },
        controller
      );
      dispatch({
        type: SET_MOVIE,
        movie: movie || null
      });
    } catch (error: any) {
      dispatch({ type: SET_ERROR, error: error?.message || '' });
    } finally {
      dispatch({ type: SET_LOADING, isLoading: false });
    }
  }

  async function getMovieReviews({
    controller
  }: {
    controller: AbortController;
  }) {
    dispatch({ type: SET_REVIES_LOADING, isLoading: true });
    try {
      const reviews = await MoviesService.getReviewsById(
        {
          id: id
        },
        controller
      );
      dispatch({
        type: SET_MOVIE_REVIEWS,
        reviews: reviews
      });
    } catch (error: any) {
      dispatch({ type: SET_ERROR, error: error?.message || '' });
    } finally {
      dispatch({ type: SET_REVIES_LOADING, isLoading: false });
    }
  }

  async function getMovieTrailers({
    controller
  }: {
    controller: AbortController;
  }) {
    dispatch({ type: SET_TRAILERS_LOADING, isLoading: true });
    try {
      const trailers = await MoviesService.getTrailersById(
        {
          id: id
        },
        controller
      );
      dispatch({
        type: SET_MOVIE_TRAILERS,
        trailers: trailers
      });
    } catch (error: any) {
      dispatch({ type: SET_ERROR, error: error?.message || '' });
    } finally {
      dispatch({ type: SET_TRAILERS_LOADING, isLoading: false });
    }
  }

  const value = useMemo(() => {
    return {
      ...state,
      selectedTab,
      setSelectedTab
    };
  }, [state, selectedTab, setSelectedTab]);

  return (
    <MovieContext.Provider value={value}>
      <MovieDispatchContext.Provider value={dispatch}>
        {children}
      </MovieDispatchContext.Provider>
    </MovieContext.Provider>
  );
}

// movies-app-solid/src/contexts/MovieContext.tsx
import {
    createSignal,
    createContext,
    JSX,
    onCleanup,
    createMemo,
    batch,
    Accessor,
    Setter,
    createEffect,
} from 'solid-js';
import MoviesService from '../services/MoviesService';
import { Movie, Review, Trailer } from '../models';
import { useParams } from '@solidjs/router';

export interface IMovieContextType {
    movie: Accessor<Movie | undefined>;
    reviews: Accessor<Review[]>;
    trailers: Accessor<Trailer[]>;
    isLoading: Accessor<boolean>;
    isReviewsLoading: Accessor<boolean>;
    isTrailersLoading: Accessor<boolean>;
    selectedTab: Accessor<string>;
    setSelectedTab: Setter<string>;
    error?: Accessor<any>;
}

export const MovieContext = createContext<IMovieContextType>({} as IMovieContextType);

export function MovieProvider(props: { children: JSX.Element }) {
    const params = useParams<{ id: string }>();
    const id = createMemo(() => params.id);

    const [movie, setMovie] = createSignal<Movie>();
    const [isLoading, setLoading] = createSignal<boolean>(false);
    const [error, setError] = createSignal<any>(null);

    const [selectedTab, setSelectedTab] = createSignal<string>('');

    const [reviews, setReviews] = createSignal<Review[]>([]);
    const [isReviewsLoading, setReviewsLoading] = createSignal<boolean>(false);
    const [isReviewsLoaded, setReviewsLoaded] = createSignal<boolean>(false);

    const [trailers, setTrailers] = createSignal<Trailer[]>([]);
    const [isTrailersLoading, setTrailersLoading] = createSignal<boolean>(false);
    const [isTrailersLoaded, setTrailersLoaded] = createSignal<boolean>(false);

    const fetchMovie = async ({ controller }: { controller: AbortController }) => {
        if (id()) {
            setLoading(true);
            try {
                const response = await MoviesService.getMovieById({
                    id: id()
                }, controller);
                setMovie(response);
            } catch (error) {
                setError(error);
            } finally {
                setLoading(false);
            }
        }
    }

    const fetchMovieReviews = async ({ controller }: { controller: AbortController }) => {
        if (id()) {
            setReviewsLoading(true);
            try {
                const response = await MoviesService.getReviewsById({
                    id: id()
                }, controller);
                batch(() => {
                    setReviews(response);
                    setReviewsLoaded(true);
                });
            } catch (error) {
                setError(error);
            } finally {
                setReviewsLoading(false);
            }
        }
    }

    const fetchMovieTrailers = async ({ controller }: { controller: AbortController }) => {
        if (id()) {
            setTrailersLoading(true);
            try {
                const response = await MoviesService.getTrailersById({
                    id: id()
                }, controller);
                batch(() => {
                    setTrailers(response);
                    setTrailersLoaded(true);
                });
            } catch (error) {
                setError(error);
            } finally {
                setTrailersLoading(false);
            }
        }
    }

    createEffect(() => {
        const controller = new AbortController();

        fetchMovie({ controller });

        onCleanup(() => {
            controller.abort();
        });
    });

    createEffect(() => {
        const controller = new AbortController();

        if (selectedTab() === 'reviews' && !isReviewsLoaded()) {
            fetchMovieReviews({ controller });
        } else if (selectedTab() === 'trailers' && !isTrailersLoaded()) {
            fetchMovieTrailers({ controller });
        }

        onCleanup(() => {
            controller.abort();
        });
    });

    const value: IMovieContextType = {
        movie,
        reviews,
        trailers,
        selectedTab,
        setSelectedTab,
        isLoading,
        isReviewsLoading,
        isTrailersLoading,
        error
    };

    return (
        <MovieContext.Provider value={value}>
            {props.children}
        </MovieContext.Provider>
    );
}
