// movies-app-react/src/hooks/useDocumentTitle.ts
import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { PAGES } from '../constants/routes';


export default function useDocumentTitle(pageTitle?: string) {
    const location = useLocation();
    const prefix = 'TMDB - ';
    const [title, setTitle] = useState('');

    useEffect(() => {
        const pathName = location.pathname;
        const page = PAGES.find((page) => page.path === pathName);
        const title = (page && page.title) || (pageTitle || '');
        setTitle(title);
        document.title = prefix + title;
    }, [location, pageTitle, setTitle]);

    return title;
}

// movies-app-solid/src/hooks/useDocumentTitle.ts
import { createEffect, createMemo } from 'solid-js';
import { useLocation } from '@solidjs/router';
import { PAGES } from '../constants';

export default function useDocumentTitle(pageTitle?: string) {
    const location = useLocation();
    const pathname = createMemo(() => location.pathname);
    const prefix = 'TMDB - ';

    createEffect(() => {
        const page = PAGES.find((page) => page.path === pathname());
        const title = (page && page.title) || (pageTitle || '');
        document.title = prefix + title;
    });
}
