// movies-app-solid/src/contexts/MoviesContext.tsx
import {
  createSignal,
  createContext,
  JSX,
  onCleanup,
  createMemo,
  batch,
  Accessor,
  Setter,
  createEffect,
  untrack,
} from 'solid-js';
import MoviesService from '../services/MoviesService';
import { Movie } from '../models';
import { useParams } from '@solidjs/router';
import useDebounce from '../hooks/useDebounce';

export interface IMoviesContextType {
  query: Accessor<string>;
  page: Accessor<number>;
  movies: Accessor<Movie[]>;
  totalPages: Accessor<number>;
  isLoading: Accessor<boolean>;
  error?: Accessor<any>;
  setQuery: (query: string) => void;
  loadMore: () => void;
}

export const MoviesContext = createContext<IMoviesContextType>({} as IMoviesContextType);

export function MoviesProvider(props: { children: JSX.Element }) {
  const params = useParams<{ category: string }>();
  const [selectedCategory, setSelectedCategory] = createSignal<string>('');
  const category = createMemo(() => {
    return !(params as any).id && `/${params.category || 'popular'}` || selectedCategory && selectedCategory();
  });

  const [movies, setMovies] = createSignal<Movie[]>([]);
  const [totalPages, setTotalPages] = createSignal<number>(1);
  const [query, setQuery] = createSignal<string>('');
  const [page, setPage] = createSignal<number>(1);
  const [isLoading, setLoading] = createSignal<boolean>(false);
  const [error, setError] = createSignal<any>(null);

  const setDebounceQuery = useDebounce(setQuery, 500);

  const fetchMovies = async ({ controller }: { controller: AbortController }) => {
    console.log('category ', category());
    if (category()) {
      setLoading(true);
      try {
        const response = await MoviesService.getMovies({
          category: category(), page: page(), query: query()
        }, controller);
        batch(() => {
          setMovies((movies: Movie[]) => {
            return page() > 1 ? [...movies, ...response?.movies] : response?.movies;
          });
          setTotalPages(response?.totalPages);
        })
      } catch (error) {
        setError(error);
      } finally {
        setLoading(false);
      }
    }
  }

  createEffect(() => {
    const currentCategory = category();
    const prevCategory = untrack(() => selectedCategory());
    if (currentCategory !== '' && currentCategory !== prevCategory) {
      batch(() => {
        setSelectedCategory(currentCategory);
        setQuery('');
        setPage(1);
      });
    }
  });

  createEffect(() => {
    if (query()) {
      setPage(1);
    }
  })

  createEffect(() => {
    const controller = new AbortController();

    fetchMovies({ controller });

    onCleanup(() => {
      controller.abort();
    });
  });

  const loadMore = () => {
    if (page() < totalPages()) {
      setPage((page) => page + 1);
    }
  }

  const value: IMoviesContextType = {
    movies,
    totalPages,
    query,
    page,
    isLoading,
    error,
    setQuery: setDebounceQuery,
    loadMore
  };

  return (
    <MoviesContext.Provider value={value}>
      {props.children}
    </MoviesContext.Provider>
  );
}

// movies-app-react/src/contexts/MoviesContext.tsx
import {
  createContext,
  ReactNode,
  useEffect,
  useMemo,
  useReducer
} from 'react';
import useDebounce from '../hooks/useDebounce';
import { Movie } from '../models';
import MoviesService from '../services/MoviesService';

export const SET_MOVIES = 'SET_MOVIES';
export const ADD_MOVIES = 'ADD_MOVIES';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_CATEGORY_LOADING = 'SET_CATEGORY_LOADING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_QUERY = 'SET_QUERY';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING = 'SET_LOADING';

export interface MoviesContextType {
  movies: Movie[];
  category: string;
  query: string;
  isLoading: boolean;
  isCategoryLoading: boolean;
  totalPages: number;
  page: number;
  error: any;
  isSearch: boolean;
}

export const MoviesContext = createContext<MoviesContextType>(
  {} as MoviesContextType
);
export const MoviesDispatchContext = createContext<any>(null);

type MoviesAction =
  | { type: typeof SET_MOVIES; movies: Movie[]; totalPages: number }
  | { type: typeof ADD_MOVIES; movies: Movie[]; totalPages: number }
  | { type: typeof SET_CATEGORY; category: string }
  | { type: typeof SET_CATEGORY_LOADING; isLoading: boolean }
  | { type: typeof SET_CURRENT_PAGE; page: number }
  | { type: typeof SET_QUERY; query: string }
  | { type: typeof SET_TOTAL_PAGES; totalPages: number }
  | { type: typeof SET_ERROR; error: string }
  | { type: typeof SET_LOADING; isLoading: boolean };

const moviesReducer = (state: MoviesContextType, action: MoviesAction) => {
  switch (action.type) {
    case SET_MOVIES:
      return {
        ...state,
        movies: action.movies,
        totalPages: action.totalPages,
        isLoading: false,
        isCategoryLoading: false
      };
    case ADD_MOVIES:
      const moviesList = [...state.movies, ...action.movies];
      const uniqueMovieIds = new Map();
      const movies = [];
      for (const movie of moviesList) {
        const id = movie.id;
        if (!uniqueMovieIds.has(id)) {
          uniqueMovieIds.set(id, true);
          movies.push(movie);
        }
      }
      return {
        ...state,
        movies: movies,
        totalPages: action.totalPages,
        isLoading: false
      };
    case SET_CATEGORY:
      return {
        ...state,
        page: 1,
        query: '',
        category: action.category
      };
    case SET_CATEGORY_LOADING:
      return {
        ...state,
        page: 1,
        query: '',
        isCategoryLoading: action.isLoading
      };
    case SET_CURRENT_PAGE:
      return {
        ...state,
        page: action.page
      };
    case SET_QUERY:
      return {
        ...state,
        page: 1,
        query: action.query
      };
    case SET_TOTAL_PAGES:
      return {
        ...state,
        totalPages: action.totalPages
      };
    case SET_ERROR:
      return {
        ...state,
        error: action.error,
        isLoading: false
      };
    case SET_LOADING:
      return {
        ...state,
        isLoading: action.isLoading,
        error: null
      };
    default:
      return state;
  }
};

const initialState: MoviesContextType = {
  movies: [],
  category: '',
  query: '',
  isLoading: true,
  isCategoryLoading: true,
  totalPages: 1,
  page: 1,
  error: null,
  isSearch: false
};

export function MoviesProvider({ children }: { children: ReactNode }): any {
  const [state, dispatch] = useReducer(moviesReducer, initialState);

  const { category, page, query } = state;
  const debouncedQuery = useDebounce(query);

  useEffect(() => {
    console.log('category ', category);
    dispatch({ type: SET_CATEGORY_LOADING, isLoading: true });
  }, [category]);

  useEffect(() => {
    if (!category) return;

    const controller = new AbortController();

    getMovies({ controller });

    return () => {
      controller.abort();
    };
  }, [page, category, debouncedQuery]);

  async function getMovies({ controller }: { controller: AbortController }) {
    dispatch({ type: SET_LOADING, isLoading: true });
    try {
      const response = await MoviesService.getMovies(
        {
          category: state.category,
          page: page,
          query: query
        },
        controller
      );
      dispatch({
        type: state.page > 1 ? ADD_MOVIES : SET_MOVIES,
        movies: response?.movies || [],
        totalPages: response?.totalPages || 0
      });
    } catch (error: any) {
      dispatch({ type: SET_ERROR, error: error?.message || '' });
    } finally {
      dispatch({ type: SET_LOADING, isLoading: false });
    }
  }

  const value = useMemo(() => {
    return {
      ...state
    };
  }, [state]);

  return (
    <MoviesContext.Provider value={value}>
      <MoviesDispatchContext.Provider value={dispatch}>
        {children}
      </MoviesDispatchContext.Provider>
    </MoviesContext.Provider>
  );
}
